name: Docker Container CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Container start
        run: docker-compose up &
      - name: Waiting for —Åontainer start
        run: sleep 30